image: docker:latest

stages:
  - build
  - test
  - deploy
  - clean

build:
  tags:
    - docker
  stage: build
  script:
    - docker build -t gitlab.netfla.me:4567/masters/code .

deploy:
  tags:
    - docker
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.netfla.me:4567
    - docker push gitlab.netfla.me:4567/masters/code

clean:
  tags:
    - docker
  stage: clean
  script:
    - docker rmi gitlab.netfla.me:4567/masters/code
  when: manual